#!/bin/bash
        find . -name "*.coffee" | grep -v node_modules | while read file; do
          echo "compiling ${file/coffee$/js/g}";
          coffee -c "$file" -o lib; git add "${file/coffee$/js/}";
        done
